import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import assert from 'node:assert/strict';

const root = fileURLToPath(new URL('../', import.meta.url));
const bundles = [
  {
    entry: 'plugins/mesosim/scripts/mcp-bridge-entry.mjs',
    output: 'plugins/mesosim/scripts/mesosim-mcp.mjs',
    notices: 'plugins/mesosim/THIRD-PARTY-NOTICES.txt',
  },
  {
    entry: 'plugins/ai-researcher/scripts/fundpro-docs-mcp-entry.mjs',
    output: 'plugins/ai-researcher/scripts/fundpro-docs-mcp.mjs',
    notices: 'plugins/ai-researcher/THIRD-PARTY-NOTICES.txt',
  },
];

for (const bundle of bundles) {
  const result = await build({ absWorkingDir: root, entryPoints: [bundle.entry], outfile: bundle.output, bundle: true, platform: 'node', format: 'esm', target: 'node22', minify: true, legalComments: 'inline', metafile: true, write: false, banner: { js: `// Generated by npm run build. Edit ${bundle.entry}, then rebuild.` } });
  // Ship licenses with each bundle. Discover only dependencies actually included by esbuild.
  const packages = new Map();
  for (const input of Object.keys(result.metafile.inputs).filter(path => path.startsWith('node_modules/'))) {
    let dir = dirname(join(root, input));
    while (dir !== root) {
      try {
        const pkg = JSON.parse(await readFile(join(dir, 'package.json'), 'utf8'));
        if (pkg.name) { packages.set(pkg.name, { dir, pkg }); break; }
      } catch { /* Walk past ESM-only subpackage metadata. */ }
      dir = dirname(dir);
    }
  }
  let notices = 'Bundled MCP bridge dependencies\nGenerated by npm run build; versions are pinned in package-lock.json.\n';
  for (const [name, { dir, pkg }] of [...packages].sort()) {
    let license;
    for (const file of ['LICENSE', 'LICENSE.md', 'LICENSE.txt']) {
      try { license = await readFile(join(dir, file), 'utf8'); break; } catch { /* Try next spelling. */ }
    }
    assert.ok(license, `Missing license for ${name}`);
    notices += `\n--- ${name} ${pkg.version} (${pkg.license}) ---\n${license}\n`;
  }
  const files = [...result.outputFiles.map(file => [file.path, file.contents]), [join(root, bundle.notices), Buffer.from(notices)]];
  for (const [path, bytes] of files) {
    if (process.argv.includes('--check')) assert.deepEqual(await readFile(path), Buffer.from(bytes), `Stale bundled artifact: ${relative(root, path)}. Run npm run build.`);
    else await writeFile(path, bytes);
  }
  console.log(`${bundle.output} ${process.argv.includes('--check') ? 'verified' : 'built'} with ${packages.size} dependency licenses.`);
}
